# os: osx
# osx_image: xcode12.2

dist: xenial
addons:
  apt:
    sources:
      - docker-xenial
      - ppa:git-core/ppa

language: go
go:
- 1.16.x

env:
  - GO111MODULE=on
# go_import_path: example.org/pkg/foo

before_install:
  - go mod tidy
  - go get github.com/swaggo/swag/cmd/swag
  - swag init
  - go get 
  # - go get github.com/gin-gonic/gin
  # - go get github.com/swaggo/gin-swagger
  # - go get github.com/swaggo/files

  # - go get -a

# gobuild_args: -x -ldflags "-X main.VersionString v1.2.3"
script: 
  # - go test -v ./controller
  # - GOOS=linux GOARCH=amd64 go build -o aihealth main.go
  - go build -o aihealth main.go
  # - docker build -t registry.cn-hangzhou.aliyuncs.com/mango9102/aihealth:0.1 ./
  - docker build -t tzaiyang/aihealth:0.1 ./

after_success:
  # - echo ${DOCKER_PASSWORD} |docker login -u ${DOCKER_USER} --password-stdin registry.cn-hangzhou.aliyuncs.com 
  # - docker push registry.cn-hangzhou.aliyuncs.com/mango9102/aihealth:0.1
  - echo ${DOCKERHUB_PASSWORD} |docker login -u ${DOCKERHUB_USER} --password-stdin
  - docker push tzaiyang/aihealth:0.1
