package main

import (
	_ "AIHealth_Server/docs" // docs is generated by Swag CLI, you have to import it.
	"AIHealth_Server/router"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title AIHealth API
// @version 1.0
// @description This is a AIHealth server.
// @host localhost:8080
// @BasePath /
func main() {
	// p1 := &(model.Page{Title: "RyanTang", Body: []byte("First Name: Ryan\nLast Name: Tang\nBirth Day: 1995-06-26\n")})
	// p1.Save()

	r := router.SetupRouter()
	r.GET("/api/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8080")
}
